spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
			  
      routes:
        - id: invoiceappms1-route
          uri: http://localhost:8036/
          predicates:
            - Path=/api/invoiceappms1/**



